const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

// language
const CHANGE_LANG = 'CHANGE_LANG';

// menu
const TOGGLE_MENU = 'TOGGLE_MENU';

// log in
const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILURE = 'LOGIN_FAILURE';

// log out
const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// data
const DATA_REQUEST = 'DATA_REQUEST';
const DATA_RECEIVE_SUCCESS = 'DATA_RECEIVE_SUCCESS';
const DATA_RECEIVE_FAILURE = 'DATA_RECEIVE_FAILURE';

// filtering page
const UPD_RATING = 'UPD_RATING';
const UPD_FILTER_BAR = 'UPD_FILTER_BAR';
const ADD_FILTER = 'ADD_FILTER';

export {
  SIGN_UP_REQUEST,
  SIGN_UP_SUCCESS,
  SIGN_UP_FAILURE,
  CHANGE_LANG,
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  LOGOUT_SUCCESS,
  TOGGLE_MENU,
  DATA_REQUEST,
  DATA_RECEIVE_SUCCESS,
  DATA_RECEIVE_FAILURE,
  UPD_RATING,
  UPD_FILTER_BAR,
  ADD_FILTER,
};
